import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'my-dashboard',
  templateUrl: './dashboard.component.html'
})
export class DashboardComponent {


columns = [
  { prop: 'NomDelFestival',width : 600 },
  { prop: 'Any', width  :80 },
  { prop: 'Ambit' },
  { prop: 'Titularitat' },
  { prop: 'Tipus' },
  { prop: 'Organitzador' },
  { prop: 'Edicio', width  :80 },
  { prop: 'DataInici' },
  { prop: 'DataFi' },
  { prop: 'Assistents' },
  { prop: 'Web',width : 300  },
  { prop: 'Nota' },
];

rows = [
  {
    "Id": 1,
    "Any": 2016,
    "Ambit": "Música",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Concert Studio",
    "Edicio": 17,
    "NomDelFestival": "Banc Sabadell Festival del Mil·lenni (gener-maig)",
    "DataInici": "1/1/2016",
    "DataFi": "20/5/2016",
    "Assistents": 42988,
    "Web": "http://www.festival-millenni.com",
    "Nota": ""
  },
  {
    "Id": 2,
    "Any": 2016,
    "Ambit": "Música",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "CAT. Centre Artesà Tradicionàrius",
    "Edicio": 29,
    "NomDelFestival": "Festival Folk Internacional Tradicionàrius",
    "DataInici": "8/1/2016",
    "DataFi": "18/3/2016",
    "Assistents": 12000,
    "Web": "http://www.tradicionarius.cat",
    "Nota": ""
  },
  {
    "Id": 3,
    "Any": 2016,
    "Ambit": "Audiovisuals",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Cineclub Barcelona Espai de Cinema",
    "Edicio": 7,
    "NomDelFestival": "MIRADOCS. Barcelona Mirades Documentals",
    "DataInici": "13/1/2016",
    "DataFi": "24/1/2016",
    "Assistents": 500,
    "Web": "http://miradocs.blogspot.com.es",
    "Nota": ""
  },
  {
    "Id": 4,
    "Any": 2016,
    "Ambit": "Música",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Assoc. Promotora de la Fundació Autoria",
    "Edicio": 21,
    "NomDelFestival": "BarnaSants",
    "DataInici": "21/1/2016",
    "DataFi": "14/4/2016",
    "Assistents": "",
    "Web": "http://www.barnasants.com",
    "Nota": ""
  },
  {
    "Id": 5,
    "Any": 2016,
    "Ambit": "Audiovisuals",
    "Titularitat": "Mixta",
    "Tipus": "Festivals",
    "Organitzador": "CCCB i Biofaction",
    "Edicio": 3,
    "NomDelFestival": "Bio-Fiction. Science Art Film Festival Barcelona",
    "DataInici": "23/1/2016",
    "DataFi": "23/1/2016",
    "Assistents": 96,
    "Web": "http://www.barcelonabeerfestival.com",
    "Nota": ""
  },
  {
    "Id": 6,
    "Any": 2016,
    "Ambit": "Música",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Assoc.  Minifestival de Música Independent",
    "Edicio": 21,
    "NomDelFestival": "Minifestival de Música i Cultura Independent de Barcelona",
    "DataInici": "23/1/2016",
    "DataFi": "7/5/2016",
    "Assistents": 425,
    "Web": "http://www.minifestival.net",
    "Nota": ""
  },
  {
    "Id": 7,
    "Any": 2016,
    "Ambit": "Lletres",
    "Titularitat": "Municipal",
    "Tipus": "Festivals",
    "Organitzador": "Institut de Cultura. Ajuntament de Barcelona",
    "Edicio": 11,
    "NomDelFestival": "BCNegra. Trobada de Novel·la Negra de Barcelona",
    "DataInici": "28/1/2016",
    "DataFi": "6/2/2016",
    "Assistents": 7639,
    "Web": "http://lameva.barcelona.cat/bcnegra/ca/inici",
    "Nota": ""
  },
  {
    "Id": 8,
    "Any": 2016,
    "Ambit": "Lletres",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Assoc. Tantàgora Serveis Culturals",
    "Edicio": 6,
    "NomDelFestival": "Flic. Festival de literatures i arts infantil i juvenil (gener-març)",
    "DataInici": "30/1/2016",
    "DataFi": "31/1/2016",
    "Assistents": 3723,
    "Web": "http://flicfestival.com",
    "Nota": ""
  },
  {
    "Id": 9,
    "Any": 2016,
    "Ambit": "Audiovisuals",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Centre Cultural Euskal Etxea Barcelona",
    "Edicio": 11,
    "NomDelFestival": "Zinemaldia",
    "DataInici": "5/2/2016",
    "DataFi": "26/2/2016",
    "Assistents": "",
    "Web": "http://www.euskaletxea.cat/zinemaldia",
    "Nota": ""
  },
  {
    "Id": 10,
    "Any": 2016,
    "Ambit": "Multidisciplinaris i altres",
    "Titularitat": "Municipal",
    "Tipus": "Festivals",
    "Organitzador": "Institut de Cultura. Ajuntament de Barcelona",
    "Edicio": "",
    "NomDelFestival": "Llum BCN",
    "DataInici": "12/2/2016",
    "DataFi": "14/2/2016",
    "Assistents": "",
    "Web": "",
    "Nota": ""
  },
  {
    "Id": 11,
    "Any": 2016,
    "Ambit": "Música",
    "Titularitat": "Mixta",
    "Tipus": "Festivals",
    "Organitzador": "Casal de Barri Prosperitat, Casal de Joves Prosperitat i Ateneu Popular 9Barris",
    "Edicio": 5,
    "NomDelFestival": "9B in Black. Festival de Música Negra de Nou Barris",
    "DataInici": "13/2/2016",
    "DataFi": "10/3/2016",
    "Assistents": 1500,
    "Web": "",
    "Nota": ""
  },
  {
    "Id": 12,
    "Any": 2016,
    "Ambit": "Música",
    "Titularitat": "Consorci o fundació amb presència municipal",
    "Tipus": "Festivals",
    "Organitzador": "CCCB",
    "Edicio": 8,
    "NomDelFestival": "Emergència!",
    "DataInici": "13/2/2016",
    "DataFi": "13/2/2016",
    "Assistents": 1781,
    "Web": "http://www.cccb.org",
    "Nota": ""
  },
  {
    "Id": 13,
    "Any": 2016,
    "Ambit": "Arts escèniques",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Lluïsos de Gràcia",
    "Edicio": 3,
    "NomDelFestival": "NanoTeatre, teatre lowcost a la Vila de Gràcia",
    "DataInici": "13/2/2016",
    "DataFi": "27/2/2016",
    "Assistents": "",
    "Web": "http://www.nanoteatre.cat/",
    "Nota": ""
  },
  {
    "Id": 14,
    "Any": 2016,
    "Ambit": "Lletres",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "La Seca Espai Brossa",
    "Edicio": 2,
    "NomDelFestival": "Festival Alcools. Poesia en escena",
    "DataInici": "16/2/2016",
    "DataFi": "3/5/2016",
    "Assistents": 372,
    "Web": "http://www.laseca.cat/",
    "Nota": ""
  },
  {
    "Id": 15,
    "Any": 2016,
    "Ambit": "Arts visuals",
    "Titularitat": "Privada",
    "Tipus": "Fires",
    "Organitzador": ".",
    "Edicio": "",
    "NomDelFestival": "Fira d'Art Modern i Antic de Barcelona",
    "DataInici": "17/2/2016",
    "DataFi": "21/2/2016",
    "Assistents": "",
    "Web": "http://www.famabarcelona.com/",
    "Nota": ""
  },
  {
    "Id": 16,
    "Any": 2016,
    "Ambit": "Lletres",
    "Titularitat": "Consorci o fundació amb presència municipal",
    "Tipus": "Festivals",
    "Organitzador": "CCCB",
    "Edicio": 9,
    "NomDelFestival": "Kosmopolis. La Festa de la Literatura Amplificada",
    "DataInici": "17/2/2016",
    "DataFi": "15/6/2016",
    "Assistents": "",
    "Web": "http://www.cccb.org/kosmopolis/ca",
    "Nota": "Kosmopolis és un festival biennal que el 2016 ha presentat una programació contínua per mantenir viu l¿esperit del festival fins a la següent edició el 2017."
  },
  {
    "Id": 17,
    "Any": 2016,
    "Ambit": "Música",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "The Project Music Company",
    "Edicio": 26,
    "NomDelFestival": "Guitar Festival BCN",
    "DataInici": "18/2/2016",
    "DataFi": "18/7/2016",
    "Assistents": 50073,
    "Web": "http://www.theproject.es",
    "Nota": ""
  },
  {
    "Id": 18,
    "Any": 2016,
    "Ambit": "Música",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Assoc. Isla Elefante Projectes Culturals",
    "Edicio": 2,
    "NomDelFestival": "Festival Cara - B",
    "DataInici": "19/2/2016",
    "DataFi": "20/2/2016",
    "Assistents": 2300,
    "Web": "http://festivalcarab.com/ca/",
    "Nota": ""
  },
  {
    "Id": 19,
    "Any": 2016,
    "Ambit": "Música",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Federació Catalana d'Entitats Corals",
    "Edicio": 11,
    "NomDelFestival": "Divendres Corals del Barcelonès",
    "DataInici": "20/2/2016",
    "DataFi": "18/3/2016",
    "Assistents": 200,
    "Web": "",
    "Nota": ""
  },
  {
    "Id": 20,
    "Any": 2016,
    "Ambit": "Audiovisuals",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Drac Màgic. Cooperativa de Promoció de Mitjans Audiovisuals",
    "Edicio": 24,
    "NomDelFestival": "Mostra Internacional de Films de Dones de Barcelona",
    "DataInici": "29/2/2016",
    "DataFi": "13/12/2016",
    "Assistents": 5822,
    "Web": "http://www.mostrafilmsdones.cat",
    "Nota": ""
  },
  {
    "Id": 21,
    "Any": 2016,
    "Ambit": "Música",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Assoc. MUTEK.es",
    "Edicio": 7,
    "NomDelFestival": "Festival Internacional de Creatividad Digital MUTEK.ES",
    "DataInici": "2/3/2016",
    "DataFi": "5/3/2016",
    "Assistents": 6000,
    "Web": "",
    "Nota": ""
  },
  {
    "Id": 22,
    "Any": 2016,
    "Ambit": "Audiovisuals",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "OVNI. Observatori de Vídeo No Identificat",
    "Edicio": 18,
    "NomDelFestival": "OVNI",
    "DataInici": "2/3/2016",
    "DataFi": "6/3/2016",
    "Assistents": 4925,
    "Web": "http://www.desorg.org",
    "Nota": ""
  },
  {
    "Id": 23,
    "Any": 2016,
    "Ambit": "Audiovisuals",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Assoc. Cultural per la Difusió del Cinema Nord-Americà",
    "Edicio": 3,
    "NomDelFestival": "Americana Film Fest",
    "DataInici": "3/3/2016",
    "DataFi": "6/3/2016",
    "Assistents": 5200,
    "Web": "http://americanafilmfest.com/es/",
    "Nota": ""
  },
  {
    "Id": 24,
    "Any": 2016,
    "Ambit": "Audiovisuals",
    "Titularitat": "Municipal",
    "Tipus": "Festivals",
    "Organitzador": "Ajuntament de Barcelona",
    "Edicio": 13,
    "NomDelFestival": "Barcelona VisualSound. Festival Audiovisual de Creació Jove",
    "DataInici": "4/3/2016",
    "DataFi": "11/3/2016",
    "Assistents": 461,
    "Web": "http://barcelonavisualsound.org",
    "Nota": ""
  },
  {
    "Id": 25,
    "Any": 2016,
    "Ambit": "Lletres",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "GRAF",
    "Edicio": 4,
    "NomDelFestival": "GRAF. Còmic d'autor i edició independent",
    "DataInici": "4/3/2016",
    "DataFi": "6/3/2016",
    "Assistents": 2000,
    "Web": "http://grafcomic.com/",
    "Nota": ""
  },
  {
    "Id": 26,
    "Any": 2016,
    "Ambit": "Multidisciplinaris i altres",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Piknic Electronik Barcelona",
    "Edicio": 4,
    "NomDelFestival": "Brunch Electronik (primavera)",
    "DataInici": "6/3/2016",
    "DataFi": "5/6/2016",
    "Assistents": "",
    "Web": "http://brunchelectronik.com/",
    "Nota": ""
  },
  {
    "Id": 27,
    "Any": 2016,
    "Ambit": "Audiovisuals",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Assoc. pel Foment del Curtmetratge Social i Casal de Joves de Prosperitat",
    "Edicio": 12,
    "NomDelFestival": "Sólo para Cortos",
    "DataInici": "8/3/2016",
    "DataFi": "13/3/2016",
    "Assistents": 750,
    "Web": "http://soloparacortos.org",
    "Nota": ""
  },
  {
    "Id": 28,
    "Any": 2016,
    "Ambit": "Audiovisuals",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Assoc.  Mecal",
    "Edicio": 18,
    "NomDelFestival": "Mecal. Festival Internacional de Curtmetratges de Barcelona",
    "DataInici": "10/3/2016",
    "DataFi": "3/4/2016",
    "Assistents": 14688,
    "Web": "http://www.mecalbcn.org",
    "Nota": ""
  },
  {
    "Id": 29,
    "Any": 2016,
    "Ambit": "Audiovisuals",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Inedit Producciones",
    "Edicio": 2,
    "NomDelFestival": "Moritz Feed Dog",
    "DataInici": "10/3/2016",
    "DataFi": "13/3/2016",
    "Assistents": 3679,
    "Web": "http://moritz.feeddog.org/the-festival/",
    "Nota": ""
  },
  {
    "Id": 30,
    "Any": 2016,
    "Ambit": "Arts escèniques",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Poble Espanyol",
    "Edicio": 7,
    "NomDelFestival": "Festival de Titelles de Barcelona",
    "DataInici": "12/3/2016",
    "DataFi": "13/3/2016",
    "Assistents": 4400,
    "Web": "http://www.poble-espanyol.com",
    "Nota": ""
  },
  {
    "Id": 31,
    "Any": 2016,
    "Ambit": "Multidisciplinaris i altres",
    "Titularitat": "Consorci o fundació amb presència municipal",
    "Tipus": "Festivals",
    "Organitzador": "Poble Espanyol",
    "Edicio": 1,
    "NomDelFestival": "De Flor de flor",
    "DataInici": "24/3/2016",
    "DataFi": "28/3/2016",
    "Assistents": 10600,
    "Web": "",
    "Nota": ""
  },
  {
    "Id": 32,
    "Any": 2016,
    "Ambit": "Lletres",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Centre Cultural Euskal Etxea Barcelona",
    "Edicio": 12,
    "NomDelFestival": "Literaldia. L'Euskal Herria d'avui, en la literatura",
    "DataInici": "1/4/2016",
    "DataFi": "29/4/2016",
    "Assistents": 1000,
    "Web": "http://www.euskaletxea.cat/literaldia",
    "Nota": ""
  },
  {
    "Id": 33,
    "Any": 2016,
    "Ambit": "Música",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Lapsus Arts, SL",
    "Edicio": 3,
    "NomDelFestival": "Lapsus Festival",
    "DataInici": "2/4/2016",
    "DataFi": "2/4/2016",
    "Assistents": 1000,
    "Web": "http://www.lapsusfestival.cat/",
    "Nota": ""
  },
  {
    "Id": 34,
    "Any": 2016,
    "Ambit": "Audiovisuals",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Serielizados",
    "Edicio": 3,
    "NomDelFestival": "Serielizados Fest",
    "DataInici": "7/4/2016",
    "DataFi": "10/4/2016",
    "Assistents": 3500,
    "Web": "http://www.szsfest.com/ca/",
    "Nota": ""
  },
  {
    "Id": 35,
    "Any": 2016,
    "Ambit": "Multidisciplinaris i altres",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Agua de Surf",
    "Edicio": 2,
    "NomDelFestival": "Surfcity Festival",
    "DataInici": "9/4/2016",
    "DataFi": "10/4/2016",
    "Assistents": 5200,
    "Web": "http://surfcityfest.com/",
    "Nota": ""
  },
  {
    "Id": 36,
    "Any": 2016,
    "Ambit": "Multidisciplinaris i altres",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Minimúsica i Primavera Sound",
    "Edicio": 4,
    "NomDelFestival": "El Dia Minimúsica (primavera)",
    "DataInici": "10/4/2016",
    "DataFi": "10/4/2016",
    "Assistents": 2800,
    "Web": "http://www.eldiaminimusica.com",
    "Nota": ""
  },
  {
    "Id": 37,
    "Any": 2016,
    "Ambit": "Lletres",
    "Titularitat": "Municipal",
    "Tipus": "Festivals",
    "Organitzador": "Institut de Cultura. Ajuntament de Barcelona",
    "Edicio": 12,
    "NomDelFestival": "Món Llibre",
    "DataInici": "16/4/2016",
    "DataFi": "17/4/2016",
    "Assistents": 21120,
    "Web": "http://lameva.barcelona.cat/monllibre/",
    "Nota": ""
  },
  {
    "Id": 38,
    "Any": 2016,
    "Ambit": "Lletres",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "ILDE",
    "Edicio": 9,
    "NomDelFestival": "Festival del Llibre d'Artista i la Petita Edició",
    "DataInici": "19/4/2016",
    "DataFi": "30/4/2016",
    "Assistents": "",
    "Web": "http://ildeasociacion.blogspot.com.es",
    "Nota": ""
  },
  {
    "Id": 39,
    "Any": 2016,
    "Ambit": "Lletres",
    "Titularitat": "Privada",
    "Tipus": "Fires",
    "Organitzador": "Raíña Lupa Produccions",
    "Edicio": 7,
    "NomDelFestival": "Arts Libris. Fira internacional del llibre i edicions d'art, fotografia i disseny de Barcelona",
    "DataInici": "20/4/2016",
    "DataFi": "24/4/2016",
    "Assistents": 10000,
    "Web": "http://artslibris.cat",
    "Nota": ""
  },
  {
    "Id": 40,
    "Any": 2016,
    "Ambit": "Audiovisuals",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Noucinemart",
    "Edicio": 6,
    "NomDelFestival": "D'A. Festival Internacional de Cinema d'Autor de Barcelona",
    "DataInici": "21/4/2016",
    "DataFi": "1/5/2016",
    "Assistents": 10585,
    "Web": "http://www.cinemadautor.cat",
    "Nota": ""
  },
  {
    "Id": 41,
    "Any": 2016,
    "Ambit": "Multidisciplinaris i altres",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Assoc. Col·lectiu Mixtur",
    "Edicio": 5,
    "NomDelFestival": "Festival Mixtur",
    "DataInici": "21/4/2016",
    "DataFi": "1/5/2016",
    "Assistents": 1147,
    "Web": "http://mixturbcn.com/es",
    "Nota": ""
  },
  {
    "Id": 42,
    "Any": 2016,
    "Ambit": "Multidisciplinaris i altres",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Fundació Tot Raval",
    "Edicio": 13,
    "NomDelFestival": "Sant Jordi al Raval",
    "DataInici": "23/4/2016",
    "DataFi": "23/4/2016",
    "Assistents": 6000,
    "Web": "",
    "Nota": ""
  },
  {
    "Id": 43,
    "Any": 2016,
    "Ambit": "Arts escèniques",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "N54 Produccions SL i Thomas Noone",
    "Edicio": 13,
    "NomDelFestival": "DANSAT",
    "DataInici": "28/4/2016",
    "DataFi": "1/5/2016",
    "Assistents": 692,
    "Web": "http://www.espaidansat.cat",
    "Nota": ""
  },
  {
    "Id": 44,
    "Any": 2016,
    "Ambit": "Audiovisuals",
    "Titularitat": "Municipal",
    "Tipus": "Festivals",
    "Organitzador": "Fundació Barcelona Olímpica, Ficts i Nikita Events",
    "Edicio": 7,
    "NomDelFestival": "BCN Sports Film",
    "DataInici": "3/5/2016",
    "DataFi": "7/5/2016",
    "Assistents": 2399,
    "Web": "http://www.bcnsportsfilm.org",
    "Nota": ""
  },
  {
    "Id": 45,
    "Any": 2016,
    "Ambit": "Lletres",
    "Titularitat": "Municipal",
    "Tipus": "Festivals",
    "Organitzador": "Institut de Cultura. Ajuntament de Barcelona",
    "Edicio": 19,
    "NomDelFestival": "Barcelona Poesia",
    "DataInici": "4/5/2016",
    "DataFi": "10/5/2016",
    "Assistents": 5324,
    "Web": "http://lameva.barcelona.cat/setmanapoesia/ca",
    "Nota": ""
  },
  {
    "Id": 46,
    "Any": 2016,
    "Ambit": "Lletres",
    "Titularitat": "Privada",
    "Tipus": "Fires",
    "Organitzador": "Ficòmic",
    "Edicio": 34,
    "NomDelFestival": "Saló Internacional del Còmic de Barcelona",
    "DataInici": "5/5/2016",
    "DataFi": "8/5/2016",
    "Assistents": 118000,
    "Web": "http://www.ficomic.com",
    "Nota": ""
  },
  {
    "Id": 47,
    "Any": 2016,
    "Ambit": "Música",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Federació Catalana d'Entitats Corals",
    "Edicio": 33,
    "NomDelFestival": "Maig Coral del Barcelonès",
    "DataInici": "6/5/2016",
    "DataFi": "5/6/2016",
    "Assistents": 300,
    "Web": "",
    "Nota": ""
  },
  {
    "Id": 48,
    "Any": 2016,
    "Ambit": "Multidisciplinaris i altres",
    "Titularitat": "Consorci o fundació amb presència municipal",
    "Tipus": "Festivals",
    "Organitzador": "CCCB",
    "Edicio": 5,
    "NomDelFestival": "Primera Persona",
    "DataInici": "6/5/2016",
    "DataFi": "7/5/2016",
    "Assistents": 1195,
    "Web": "http://primerapersonabcn.blogspot.com.es",
    "Nota": ""
  },
  {
    "Id": 49,
    "Any": 2016,
    "Ambit": "Multidisciplinaris i altres",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Coincidències",
    "Edicio": 4,
    "NomDelFestival": "Terrats en cultura",
    "DataInici": "6/5/2016",
    "DataFi": "6/11/2016",
    "Assistents": 1440,
    "Web": "http://coincidencies.com/terrats-en-cultura/",
    "Nota": ""
  },
  {
    "Id": 50,
    "Any": 2016,
    "Ambit": "Arts escèniques",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "La Seca Espai Brossa",
    "Edicio": 13,
    "NomDelFestival": "BarriBrossa",
    "DataInici": "7/5/2016",
    "DataFi": "14/5/2016",
    "Assistents": 541,
    "Web": "http://www.laseca.cat",
    "Nota": ""
  },
  {
    "Id": 51,
    "Any": 2016,
    "Ambit": "Arts visuals",
    "Titularitat": "Municipal",
    "Tipus": "Festivals",
    "Organitzador": "Centre Cívic Pati Llimona",
    "Edicio": 7,
    "NomDelFestival": "Enfocats",
    "DataInici": "7/5/2016",
    "DataFi": "4/6/2016",
    "Assistents": 745,
    "Web": "http://patillimona.net/",
    "Nota": ""
  },
  {
    "Id": 52,
    "Any": 2016,
    "Ambit": "Música",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Asociación BalkaBarna, Dinamita Balkana y Balkan Party",
    "Edicio": 3,
    "NomDelFestival": "BalkaBarna Festival",
    "DataInici": "8/5/2016",
    "DataFi": "8/5/2016",
    "Assistents": 1400,
    "Web": "http://balkabarna-festival.com",
    "Nota": ""
  },
  {
    "Id": 53,
    "Any": 2016,
    "Ambit": "Audiovisuals",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Assoc. Panorama 180",
    "Edicio": 7,
    "NomDelFestival": "Festival de Cinema en Creative Commons de Barcelona. BccN",
    "DataInici": "11/5/2016",
    "DataFi": "15/5/2016",
    "Assistents": 1200,
    "Web": "http://www.bccn.cc/ca/nou-inici/",
    "Nota": ""
  },
  {
    "Id": 54,
    "Any": 2016,
    "Ambit": "Arts escèniques",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Fundació Catalunya - La Pedrera",
    "Edicio": 5,
    "NomDelFestival": "Noves Escenes, Noves Mirades",
    "DataInici": "11/5/2016",
    "DataFi": "31/5/2016",
    "Assistents": 519,
    "Web": "http://www.lapedrera.com",
    "Nota": ""
  },
  {
    "Id": 55,
    "Any": 2016,
    "Ambit": "Audiovisuals",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Assoc. d'Idees - La Escocesa",
    "Edicio": 9,
    "NomDelFestival": "Mostra de Cinema Indígena de Barcelona",
    "DataInici": "12/5/2016",
    "DataFi": "15/5/2016",
    "Assistents": 500,
    "Web": "",
    "Nota": ""
  },
  {
    "Id": 56,
    "Any": 2016,
    "Ambit": "Música",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Taller de Músics i Mercat de les Flors",
    "Edicio": 23,
    "NomDelFestival": "Ciutat Flamenco",
    "DataInici": "18/5/2016",
    "DataFi": "22/5/2016",
    "Assistents": 2932,
    "Web": "http://ciutatflamenco.com",
    "Nota": ""
  },
  {
    "Id": 57,
    "Any": 2016,
    "Ambit": "Audiovisuals",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Assoc. Art NonStop",
    "Edicio": 3,
    "NomDelFestival": "NonStop Barcelona Animació",
    "DataInici": "18/5/2016",
    "DataFi": "22/5/2016",
    "Assistents": 2500,
    "Web": "http://nonstopbarcelona.com/",
    "Nota": ""
  },
  {
    "Id": 58,
    "Any": 2016,
    "Ambit": "Arts visuals",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Photographic Social Vision",
    "Edicio": 4,
    "NomDelFestival": "DOCfield. Festival de Fotografia Documental",
    "DataInici": "19/5/2016",
    "DataFi": "19/7/2016",
    "Assistents": 141143,
    "Web": "http://docfieldbarcelona.org/",
    "Nota": ""
  },
  {
    "Id": 59,
    "Any": 2016,
    "Ambit": "Audiovisuals",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Paral·lel 40",
    "Edicio": 19,
    "NomDelFestival": "DocsBarcelona",
    "DataInici": "23/5/2016",
    "DataFi": "29/5/2016",
    "Assistents": 8368,
    "Web": "http://www.docsbarcelona.com",
    "Nota": ""
  },
  {
    "Id": 60,
    "Any": 2016,
    "Ambit": "Arts visuals",
    "Titularitat": "Privada",
    "Tipus": "Fires",
    "Organitzador": "Screen Projects S.L.",
    "Edicio": 14,
    "NomDelFestival": "Loop Fair",
    "DataInici": "26/5/2016",
    "DataFi": "10/6/2016",
    "Assistents": 5000,
    "Web": "http://www.loop-barcelona.com",
    "Nota": ""
  },
  {
    "Id": 61,
    "Any": 2016,
    "Ambit": "Arts visuals",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Screen Projects S.L.",
    "Edicio": 14,
    "NomDelFestival": "Loop Festival (abans Screen Festival)",
    "DataInici": "26/5/2016",
    "DataFi": "10/6/2016",
    "Assistents": 110000,
    "Web": "http://www.loop-barcelona.com",
    "Nota": ""
  },
  {
    "Id": 62,
    "Any": 2016,
    "Ambit": "Multidisciplinaris i altres",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "OFFF",
    "Edicio": 16,
    "NomDelFestival": "OFFF Let's feed the future",
    "DataInici": "26/5/2016",
    "DataFi": "28/5/2016",
    "Assistents": 3500,
    "Web": "http://www.offf.ws",
    "Nota": ""
  },
  {
    "Id": 63,
    "Any": 2016,
    "Ambit": "Arts visuals",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Art Deal Project",
    "Edicio": 3,
    "NomDelFestival": "Art Photo BCN",
    "DataInici": "27/5/2016",
    "DataFi": "28/5/2016",
    "Assistents": 2600,
    "Web": "http://www.artphotobcn.com/",
    "Nota": ""
  },
  {
    "Id": 64,
    "Any": 2016,
    "Ambit": "Música",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Primavera Sound",
    "Edicio": 16,
    "NomDelFestival": "San Miguel Primavera Sound",
    "DataInici": "30/5/2016",
    "DataFi": "5/6/2016",
    "Assistents": 207435,
    "Web": "http://www.primaverasound.com",
    "Nota": ""
  },
  {
    "Id": 65,
    "Any": 2016,
    "Ambit": "Arts escèniques",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Ociopuro, SL",
    "Edicio": 6,
    "NomDelFestival": "Barcelona Burlesque Festival",
    "DataInici": "1/6/2016",
    "DataFi": "12/6/2016",
    "Assistents": 2100,
    "Web": "http://www.elmolinobcn.com",
    "Nota": ""
  },
  {
    "Id": 66,
    "Any": 2016,
    "Ambit": "Arts visuals",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Barcelona Centre del Disseny",
    "Edicio": 11,
    "NomDelFestival": "BCN Design Week",
    "DataInici": "2/6/2016",
    "DataFi": "12/6/2016",
    "Assistents": 12000,
    "Web": "http://www.barcelonadesignweek.com",
    "Nota": ""
  },
  {
    "Id": 67,
    "Any": 2016,
    "Ambit": "Audiovisuals",
    "Titularitat": "Pública no municipal",
    "Tipus": "Festivals",
    "Organitzador": "Assoc.  Mecal",
    "Edicio": 2,
    "NomDelFestival": "Mecal Rooftop",
    "DataInici": "2/6/2016",
    "DataFi": "29/9/2016",
    "Assistents": 2250,
    "Web": "http://www.mecalbcn.org",
    "Nota": ""
  },
  {
    "Id": 68,
    "Any": 2016,
    "Ambit": "Arts visuals",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Assoc. Ca la Dona",
    "Edicio": 23,
    "NomDelFestival": "Fem Art",
    "DataInici": "3/6/2016",
    "DataFi": "28/10/2016",
    "Assistents": 470,
    "Web": "http://femartmostra.blogspot.com.es/p/mostra-fem-a",
    "Nota": ""
  },
  {
    "Id": 69,
    "Any": 2016,
    "Ambit": "Audiovisuals",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "La Jarra Azul",
    "Edicio": 15,
    "NomDelFestival": "Mostra de Curtmetratges Dr. Mabuse",
    "DataInici": "4/6/2016",
    "DataFi": "18/6/2016",
    "Assistents": 700,
    "Web": "http://www.mostra-drmabuse.org",
    "Nota": ""
  },
  {
    "Id": 70,
    "Any": 2016,
    "Ambit": "Multidisciplinaris i altres",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "FAD",
    "Edicio": 6,
    "NomDelFestival": "FADfest. The festival of all design",
    "DataInici": "6/6/2016",
    "DataFi": "12/6/2016",
    "Assistents": 10640,
    "Web": "http://www.fadfest.cat",
    "Nota": ""
  },
  {
    "Id": 71,
    "Any": 2016,
    "Ambit": "Multidisciplinaris i altres",
    "Titularitat": "Municipal",
    "Tipus": "Festivals",
    "Organitzador": "Convent de Sant Agustí",
    "Edicio": 10,
    "NomDelFestival": "Mostra Sonora i Visual",
    "DataInici": "7/6/2016",
    "DataFi": "11/6/2016",
    "Assistents": "",
    "Web": "http://conventagusti.com",
    "Nota": ""
  },
  {
    "Id": 72,
    "Any": 2016,
    "Ambit": "Música",
    "Titularitat": "Municipal",
    "Tipus": "Festivals",
    "Organitzador": "Ajuntament de Barcelona",
    "Edicio": 21,
    "NomDelFestival": "Festival de Música als Parcs",
    "DataInici": "8/6/2016",
    "DataFi": "31/8/2016",
    "Assistents": 12000,
    "Web": "",
    "Nota": ""
  },
  {
    "Id": 73,
    "Any": 2016,
    "Ambit": "Audiovisuals",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Qrquinfad i Filmoteca de Catalunya",
    "Edicio": 2,
    "NomDelFestival": "Arqu [in] FILM",
    "DataInici": "10/6/2016",
    "DataFi": "17/6/2016",
    "Assistents": 399,
    "Web": "",
    "Nota": ""
  },
  {
    "Id": 74,
    "Any": 2016,
    "Ambit": "Multidisciplinaris i altres",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Centre Cívic Besòs",
    "Edicio": 10,
    "NomDelFestival": "Besmina. Festival d'Art Jove al Carrer",
    "DataInici": "10/6/2016",
    "DataFi": "16/6/2016",
    "Assistents": 120,
    "Web": "",
    "Nota": ""
  },
  {
    "Id": 75,
    "Any": 2016,
    "Ambit": "Música",
    "Titularitat": "Municipal",
    "Tipus": "Festivals",
    "Organitzador": "Casal de Joves de la Guineueta",
    "Edicio": 22,
    "NomDelFestival": "Simbiruta. Festival Jove de la Guineueta",
    "DataInici": "10/6/2016",
    "DataFi": "11/6/2016",
    "Assistents": 1000,
    "Web": "",
    "Nota": ""
  },
  {
    "Id": 76,
    "Any": 2016,
    "Ambit": "Música",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Fundació Bona Nit Barcelona",
    "Edicio": 4,
    "NomDelFestival": "Bona Nit Barcelona",
    "DataInici": "11/6/2016",
    "DataFi": "11/6/2016",
    "Assistents": 3256,
    "Web": "http://www.bonanitbarcelona.es",
    "Nota": ""
  },
  {
    "Id": 77,
    "Any": 2016,
    "Ambit": "Música",
    "Titularitat": "Municipal",
    "Tipus": "Festivals",
    "Organitzador": "Centre Cívic d'Urgell",
    "Edicio": 5,
    "NomDelFestival": "Ermessenda Pop Festival",
    "DataInici": "11/6/2016",
    "DataFi": "11/6/2016",
    "Assistents": 200,
    "Web": "http://www.ccurgell.cat",
    "Nota": ""
  },
  {
    "Id": 78,
    "Any": 2016,
    "Ambit": "Música",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Comunicamanagers & Mas i Mas",
    "Edicio": 4,
    "NomDelFestival": "Festival Internacional de Boleros",
    "DataInici": "11/6/2016",
    "DataFi": "18/6/2016",
    "Assistents": "",
    "Web": "http://festivaldebolerosronvaradero.com",
    "Nota": ""
  },
  {
    "Id": 79,
    "Any": 2016,
    "Ambit": "Música",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Concert Studio",
    "Edicio": 4,
    "NomDelFestival": "Festival Jardins de Pedralbes",
    "DataInici": "11/6/2016",
    "DataFi": "16/7/2016",
    "Assistents": 30100,
    "Web": "http://www.festivalpedralbes.com",
    "Nota": ""
  },
  {
    "Id": 80,
    "Any": 2016,
    "Ambit": "Audiovisuals",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Assoc.  Mecal",
    "Edicio": 9,
    "NomDelFestival": "Mecal Air",
    "DataInici": "11/6/2016",
    "DataFi": "24/9/2016",
    "Assistents": 5250,
    "Web": "http://www.mecalbcn.org",
    "Nota": ""
  },
  {
    "Id": 81,
    "Any": 2016,
    "Ambit": "Música",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Assoc. SIMFONIC",
    "Edicio": 6,
    "NomDelFestival": "SIMFONIC",
    "DataInici": "11/6/2016",
    "DataFi": "11/6/2016",
    "Assistents": 9500,
    "Web": "http://www.simfonic.org/",
    "Nota": ""
  },
  {
    "Id": 82,
    "Any": 2016,
    "Ambit": "Música",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Zingaria Produccions SL",
    "Edicio": 5,
    "NomDelFestival": "Zingaria Festival",
    "DataInici": "13/6/2016",
    "DataFi": "28/8/2016",
    "Assistents": 1500,
    "Web": "http://www.harlemjazzclub.es/",
    "Nota": ""
  },
  {
    "Id": 83,
    "Any": 2016,
    "Ambit": "Música",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Advanced Music S.L.",
    "Edicio": 23,
    "NomDelFestival": "Sónar. Festival Internacional de Música Avançada i Art Multimèdia",
    "DataInici": "16/6/2016",
    "DataFi": "18/6/2016",
    "Assistents": 115500,
    "Web": "http://sonar.es",
    "Nota": ""
  },
  {
    "Id": 84,
    "Any": 2016,
    "Ambit": "Música",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Fundació Catalunya - La Pedrera",
    "Edicio": 12,
    "NomDelFestival": "Nits d'Estiu a La Pedrera",
    "DataInici": "19/6/2016",
    "DataFi": "12/9/2016",
    "Assistents": 6743,
    "Web": "http://www.lapedrera.com",
    "Nota": ""
  },
  {
    "Id": 85,
    "Any": 2016,
    "Ambit": "Multidisciplinaris i altres",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": ".",
    "Edicio": 11,
    "NomDelFestival": "Festival d'estiu LLIMONADES",
    "DataInici": "22/6/2016",
    "DataFi": "15/7/2016",
    "Assistents": 1100,
    "Web": "",
    "Nota": ""
  },
  {
    "Id": 86,
    "Any": 2016,
    "Ambit": "Música",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Mundo Arts Spain, SLU",
    "Edicio": 12,
    "NomDelFestival": "Barcelona Festival of Song",
    "DataInici": "25/6/2016",
    "DataFi": "4/7/2016",
    "Assistents": 1500,
    "Web": "http://www.barcelonafestivalofsong.com",
    "Nota": ""
  },
  {
    "Id": 87,
    "Any": 2016,
    "Ambit": "Audiovisuals",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Mago Audiovisual Production",
    "Edicio": 5,
    "NomDelFestival": "Cinema Lliure a la Platja",
    "DataInici": "30/6/2016",
    "DataFi": "7/8/2016",
    "Assistents": 22000,
    "Web": "http://www.cinemalliure.com",
    "Nota": ""
  },
  {
    "Id": 88,
    "Any": 2016,
    "Ambit": "Audiovisuals",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Casal Lambda",
    "Edicio": 21,
    "NomDelFestival": "FIRE!! Mostra Internacional de Cinema Gai i Lesbià",
    "DataInici": "30/6/2016",
    "DataFi": "10/7/2016",
    "Assistents": 6000,
    "Web": "http://www.cinemalambda.com",
    "Nota": ""
  },
  {
    "Id": 89,
    "Any": 2016,
    "Ambit": "Música",
    "Titularitat": "Municipal",
    "Tipus": "Festivals",
    "Organitzador": "Assoc. Promotora per a la Fundació Catalunya Arte Flamenco",
    "Edicio": 16,
    "NomDelFestival": "Festival Flamenco Nou Barris",
    "DataInici": "1/7/2016",
    "DataFi": "2/7/2016",
    "Assistents": "",
    "Web": "http://www.catalunyaarteflamenco.com",
    "Nota": ""
  },
  {
    "Id": 90,
    "Any": 2016,
    "Ambit": "Música",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Taller de Músics",
    "Edicio": 4,
    "NomDelFestival": "Festival Talent",
    "DataInici": "1/7/2016",
    "DataFi": "4/7/2016",
    "Assistents": 2250,
    "Web": "http://tallerdemusics.com",
    "Nota": ""
  },
  {
    "Id": 91,
    "Any": 2016,
    "Ambit": "Multidisciplinaris i altres",
    "Titularitat": "Municipal",
    "Tipus": "Festivals",
    "Organitzador": "Institut de Cultura. Ajuntament de Barcelona",
    "Edicio": 40,
    "NomDelFestival": "Grec Festival de Barcelona",
    "DataInici": "1/7/2016",
    "DataFi": "31/7/2016",
    "Assistents": 102555,
    "Web": "http://lameva.barcelona.cat/grec/",
    "Nota": ""
  },
  {
    "Id": 92,
    "Any": 2016,
    "Ambit": "Audiovisuals",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Assoc. Cultural Modiband",
    "Edicio": 14,
    "NomDelFestival": "Sala Montjuïc",
    "DataInici": "1/7/2016",
    "DataFi": "5/8/2016",
    "Assistents": 34000,
    "Web": "http://www.salamontjuic.org",
    "Nota": ""
  },
  {
    "Id": 93,
    "Any": 2016,
    "Ambit": "Audiovisuals",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Asian Films",
    "Edicio": 8,
    "NomDelFestival": "ImagineIndia Film Festival Barcelona",
    "DataInici": "2/7/2016",
    "DataFi": "13/8/2016",
    "Assistents": "",
    "Web": "http://www.imagineindia.net",
    "Nota": ""
  },
  {
    "Id": 94,
    "Any": 2016,
    "Ambit": "Música",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Federació Catalana d'Entitats Corals",
    "Edicio": 51,
    "NomDelFestival": "Festival Internacional de Cant Coral a Barcelona",
    "DataInici": "4/7/2016",
    "DataFi": "10/7/2016",
    "Assistents": 3000,
    "Web": "http://www.fcec.cat",
    "Nota": ""
  },
  {
    "Id": 95,
    "Any": 2016,
    "Ambit": "Audiovisuals",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Assoc. Marea Crítica",
    "Edicio": 4,
    "NomDelFestival": "Barcelona Surf Film Festival",
    "DataInici": "6/7/2016",
    "DataFi": "9/7/2016",
    "Assistents": "",
    "Web": "http://www.bcnsurffilmfestival.com",
    "Nota": ""
  },
  {
    "Id": 96,
    "Any": 2016,
    "Ambit": "Música",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Assoc. Capibola Blues",
    "Edicio": 14,
    "NomDelFestival": "Festival de Blues de Barcelona",
    "DataInici": "6/7/2016",
    "DataFi": "17/7/2016",
    "Assistents": 2500,
    "Web": "http://www.bluesbcn.com",
    "Nota": ""
  },
  {
    "Id": 97,
    "Any": 2016,
    "Ambit": "Música",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Barcelona Events Musicals SL",
    "Edicio": 7,
    "NomDelFestival": "Cruïlla BCN",
    "DataInici": "8/7/2016",
    "DataFi": "10/7/2016",
    "Assistents": 47000,
    "Web": "http://www.cruillabarcelona.com",
    "Nota": ""
  },
  {
    "Id": 98,
    "Any": 2016,
    "Ambit": "Multidisciplinaris i altres",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Piknic Electronik Barcelona",
    "Edicio": 5,
    "NomDelFestival": "Piknic Electronik",
    "DataInici": "8/7/2016",
    "DataFi": "23/9/2016",
    "Assistents": "",
    "Web": "http://piknicelectronik.es",
    "Nota": ""
  },
  {
    "Id": 99,
    "Any": 2016,
    "Ambit": "Multidisciplinaris i altres",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "nunArt",
    "Edicio": 8,
    "NomDelFestival": "nunOff. Festival de Creació Emergent de Barcelona",
    "DataInici": "11/7/2016",
    "DataFi": "16/7/2016",
    "Assistents": 900,
    "Web": "http://nunartbcn.com",
    "Nota": ""
  },
  {
    "Id": 100,
    "Any": 2016,
    "Ambit": "Audiovisuals",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Colectiu Cine Migrante i Fundació Guné",
    "Edicio": 3,
    "NomDelFestival": "Mostra Internacional CineMigrante",
    "DataInici": "12/7/2016",
    "DataFi": "17/7/2016",
    "Assistents": 1560,
    "Web": "http://www.cinemigrante.org/",
    "Nota": ""
  },
  {
    "Id": 101,
    "Any": 2016,
    "Ambit": "Música",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "ZOOM IN SA - Rafael Veljanovich",
    "Edicio": 6,
    "NomDelFestival": "Barcelona, Gardel, Buenos Aires",
    "DataInici": "15/7/2016",
    "DataFi": "22/7/2016",
    "Assistents": "",
    "Web": "http://www.bcngardelbue.com",
    "Nota": ""
  },
  {
    "Id": 102,
    "Any": 2016,
    "Ambit": "Música",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Live Nation",
    "Edicio": 3,
    "NomDelFestival": "Barcelona Beach Festival",
    "DataInici": "16/7/2016",
    "DataFi": "16/7/2016",
    "Assistents": 40000,
    "Web": "",
    "Nota": ""
  },
  {
    "Id": 103,
    "Any": 2016,
    "Ambit": "Música",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Charming Music",
    "Edicio": 3,
    "NomDelFestival": "Soundeat",
    "DataInici": "16/7/2016",
    "DataFi": "16/7/2016",
    "Assistents": "",
    "Web": "http://www.festivalpedralbes.com",
    "Nota": ""
  },
  {
    "Id": 104,
    "Any": 2016,
    "Ambit": "Música",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Fundació BZM",
    "Edicio": 4,
    "NomDelFestival": "Bachcelona",
    "DataInici": "21/7/2016",
    "DataFi": "26/7/2016",
    "Assistents": 5000,
    "Web": "http://www.bachcelona.com",
    "Nota": ""
  },
  {
    "Id": 105,
    "Any": 2016,
    "Ambit": "Arts escèniques",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Assoc. Catalana Perpetuum Mobile",
    "Edicio": 3,
    "NomDelFestival": "PIIGS. Festival de Dramatúrgia sobre la Crisi",
    "DataInici": "21/7/2016",
    "DataFi": "23/7/2016",
    "Assistents": 250,
    "Web": "http://www.perpetuum.cat/esp/category/festivales/",
    "Nota": ""
  },
  {
    "Id": 106,
    "Any": 2016,
    "Ambit": "Multidisciplinaris i altres",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Assoc. d'Idees - La Escocesa",
    "Edicio": 5,
    "NomDelFestival": "Festival de Murals de La Escocesa",
    "DataInici": "22/7/2016",
    "DataFi": "23/7/2016",
    "Assistents": "",
    "Web": "http://www.laescocesa.org/ca",
    "Nota": ""
  },
  {
    "Id": 107,
    "Any": 2016,
    "Ambit": "Música",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Pelaimas, SL",
    "Edicio": 14,
    "NomDelFestival": "San Miguel Mas i Mas Festival",
    "DataInici": "25/7/2016",
    "DataFi": "4/9/2016",
    "Assistents": 20000,
    "Web": "http://www.masimas.com/festival",
    "Nota": ""
  },
  {
    "Id": 108,
    "Any": 2016,
    "Ambit": "Audiovisuals",
    "Titularitat": "Consorci o fundació amb presència municipal",
    "Tipus": "Festivals",
    "Organitzador": "CCCB",
    "Edicio": 14,
    "NomDelFestival": "Gandules",
    "DataInici": "9/8/2016",
    "DataFi": "25/8/2016",
    "Assistents": 4414,
    "Web": "http://www.cccb.org",
    "Nota": ""
  },
  {
    "Id": 109,
    "Any": 2016,
    "Ambit": "Multidisciplinaris i altres",
    "Titularitat": "Consorci o fundació amb presència municipal",
    "Tipus": "Festivals",
    "Organitzador": "CCCB",
    "Edicio": 1,
    "NomDelFestival": "Africalisme al CCCB",
    "DataInici": "12/8/2016",
    "DataFi": "26/8/2016",
    "Assistents": 2388,
    "Web": "",
    "Nota": ""
  },
  {
    "Id": 110,
    "Any": 2016,
    "Ambit": "Música",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Excentris, DGTL Amsterdam i Proyectual",
    "Edicio": 2,
    "NomDelFestival": "DGTL Festival",
    "DataInici": "12/8/2016",
    "DataFi": "13/8/2016",
    "Assistents": 30000,
    "Web": "http://bcn.dgtl.nl",
    "Nota": ""
  },
  {
    "Id": 111,
    "Any": 2016,
    "Ambit": "Música",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Assoc. Cultural Heliogàbal",
    "Edicio": 11,
    "NomDelFestival": "Festigàbal",
    "DataInici": "18/8/2016",
    "DataFi": "19/8/2016",
    "Assistents": "",
    "Web": "http://www.heliogabal.com",
    "Nota": ""
  },
  {
    "Id": 112,
    "Any": 2016,
    "Ambit": "Multidisciplinaris i altres",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "GID Renaixença",
    "Edicio": 6,
    "NomDelFestival": "Festival Internacional de Música i Dansa Tradicional al Poble-sec",
    "DataInici": "22/8/2016",
    "DataFi": "28/8/2016",
    "Assistents": "",
    "Web": "http://www.festivalspoblesec.org",
    "Nota": ""
  },
  {
    "Id": 113,
    "Any": 2016,
    "Ambit": "Lletres",
    "Titularitat": "Privada",
    "Tipus": "Fires",
    "Organitzador": "Assoc.  d'Editors en llengua catalana",
    "Edicio": 34,
    "NomDelFestival": "Setmana del Llibre en Català",
    "DataInici": "2/9/2016",
    "DataFi": "11/9/2016",
    "Assistents": 300000,
    "Web": "http://www.lasetmana.cat",
    "Nota": ""
  },
  {
    "Id": 114,
    "Any": 2016,
    "Ambit": "Música",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Assoc. de Músics de Jazz i Música Moderna de Catalunya",
    "Edicio": 26,
    "NomDelFestival": "Festival l'Hora del Jazz. Memorial Tete Montoliu",
    "DataInici": "4/9/2016",
    "DataFi": "29/9/2016",
    "Assistents": 6150,
    "Web": "http://www.amjm.org",
    "Nota": ""
  },
  {
    "Id": 115,
    "Any": 2016,
    "Ambit": "Música",
    "Titularitat": "Municipal",
    "Tipus": "Festivals",
    "Organitzador": "Assoc. Sant Andreu Jazz Band i Dte. de Sant Andreu",
    "Edicio": 3,
    "NomDelFestival": "Jazzing Festival",
    "DataInici": "8/9/2016",
    "DataFi": "18/9/2016",
    "Assistents": 20000,
    "Web": "http://jazzingfestival.com",
    "Nota": ""
  },
  {
    "Id": 116,
    "Any": 2016,
    "Ambit": "Lletres",
    "Titularitat": "Privada",
    "Tipus": "Fires",
    "Organitzador": "Gremi de Llibreters de Vell de Catalunya",
    "Edicio": 65,
    "NomDelFestival": "Fira del Llibre d'Ocasió Antic i Modern",
    "DataInici": "19/9/2016",
    "DataFi": "25/9/2016",
    "Assistents": "",
    "Web": "http://www.gremillibrevell.cat",
    "Nota": ""
  },
  {
    "Id": 117,
    "Any": 2016,
    "Ambit": "Audiovisuals",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Assoc. Festival de Cinema Jueu a Barcelona",
    "Edicio": 18,
    "NomDelFestival": "Festival de Cinema Jueu de Barcelona",
    "DataInici": "20/9/2016",
    "DataFi": "1/10/2016",
    "Assistents": "",
    "Web": "http://www.fcjbarcelona.org",
    "Nota": ""
  },
  {
    "Id": 118,
    "Any": 2016,
    "Ambit": "Música",
    "Titularitat": "Municipal",
    "Tipus": "Festivals",
    "Organitzador": "Institut de Cultura. Ajuntament de Barcelona",
    "Edicio": 24,
    "NomDelFestival": "BAM. Barcelona Acció Musical",
    "DataInici": "22/9/2016",
    "DataFi": "25/9/2016",
    "Assistents": 56950,
    "Web": "http://lameva.barcelona.cat/bam/ca/",
    "Nota": ""
  },
  {
    "Id": 119,
    "Any": 2016,
    "Ambit": "Arts escèniques",
    "Titularitat": "Municipal",
    "Tipus": "Festivals",
    "Organitzador": "Institut de Cultura. Ajuntament de Barcelona",
    "Edicio": 7,
    "NomDelFestival": "Mercè Arts de Carrer. MAC",
    "DataInici": "22/9/2016",
    "DataFi": "25/9/2016",
    "Assistents": 228946,
    "Web": "http://lameva.barcelona.cat/merce/ca/",
    "Nota": ""
  },
  {
    "Id": 120,
    "Any": 2016,
    "Ambit": "Música",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Gràcia Territori Sonor",
    "Edicio": 21,
    "NomDelFestival": "Dispositiu LEM. Encontre Internacional de Música Experimental",
    "DataInici": "29/9/2016",
    "DataFi": "29/10/2016",
    "Assistents": 2111,
    "Web": "",
    "Nota": ""
  },
  {
    "Id": 121,
    "Any": 2016,
    "Ambit": "Arts visuals",
    "Titularitat": "Privada",
    "Tipus": "Fires",
    "Organitzador": "Espacio de Arte Contemporáneo Diezy7",
    "Edicio": 9,
    "NomDelFestival": "Swab Barcelona. Fira Internacional d'Art Contemporani",
    "DataInici": "29/9/2016",
    "DataFi": "2/10/2016",
    "Assistents": 18000,
    "Web": "http://swab.es",
    "Nota": ""
  },
  {
    "Id": 122,
    "Any": 2016,
    "Ambit": "Arts escèniques",
    "Titularitat": "Municipal",
    "Tipus": "Festivals",
    "Organitzador": "Ajuntament de Barcelona",
    "Edicio": 17,
    "NomDelFestival": "Circorts",
    "DataInici": "30/9/2016",
    "DataFi": "2/10/2016",
    "Assistents": "",
    "Web": "",
    "Nota": ""
  },
  {
    "Id": 123,
    "Any": 2016,
    "Ambit": "Audiovisuals",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Mago Experience",
    "Edicio": 2,
    "NomDelFestival": "Barcelona Anime Festival",
    "DataInici": "1/10/2016",
    "DataFi": "2/10/2016",
    "Assistents": 10000,
    "Web": "http://www.b-anime.org/",
    "Nota": ""
  },
  {
    "Id": 124,
    "Any": 2016,
    "Ambit": "Música",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Taller de Músics i Bankrobber",
    "Edicio": 5,
    "NomDelFestival": "Connexions",
    "DataInici": "1/10/2016",
    "DataFi": "30/10/2016",
    "Assistents": 3200,
    "Web": "http://www.festivalconnexions.com",
    "Nota": ""
  },
  {
    "Id": 125,
    "Any": 2016,
    "Ambit": "Arts escèniques",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Artípolis",
    "Edicio": 21,
    "NomDelFestival": "Mostra de Teatre de Barcelona",
    "DataInici": "3/10/2016",
    "DataFi": "26/10/2016",
    "Assistents": 722,
    "Web": "http://www.teatredelraval.com",
    "Nota": ""
  },
  {
    "Id": 126,
    "Any": 2016,
    "Ambit": "Audiovisuals",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Rueda Film Festival",
    "Edicio": 2,
    "NomDelFestival": "Rueda. Festival Internacional de Cinema Ciclista",
    "DataInici": "6/10/2016",
    "DataFi": "9/10/2016",
    "Assistents": 3000,
    "Web": "http://ruedabcn.cc/",
    "Nota": ""
  },
  {
    "Id": 127,
    "Any": 2016,
    "Ambit": "Lletres",
    "Titularitat": "Privada",
    "Tipus": "Fires",
    "Organitzador": "Federació de Gremis d'Editors d'Espanya",
    "Edicio": 34,
    "NomDelFestival": "Liber",
    "DataInici": "12/10/2016",
    "DataFi": "14/10/2016",
    "Assistents": "",
    "Web": "http://www.liber.es",
    "Nota": ""
  },
  {
    "Id": 128,
    "Any": 2016,
    "Ambit": "Audiovisuals",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Imago Gestiona",
    "Edicio": 13,
    "NomDelFestival": "Diàspora. Mostra de Cinema Colombià",
    "DataInici": "13/10/2016",
    "DataFi": "23/10/2016",
    "Assistents": 3476,
    "Web": "http://www.imagocatalunya.org",
    "Nota": ""
  },
  {
    "Id": 129,
    "Any": 2016,
    "Ambit": "Arts visuals",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "ADC*E. Art Directors Club of Europe i ADG-FAD",
    "Edicio": 3,
    "NomDelFestival": "European Creativity Festival",
    "DataInici": "13/10/2016",
    "DataFi": "15/10/2016",
    "Assistents": 250,
    "Web": "",
    "Nota": ""
  },
  {
    "Id": 130,
    "Any": 2016,
    "Ambit": "Arts visuals",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Assoc. Sobreàtic",
    "Edicio": 2,
    "NomDelFestival": "Photogenic Festival",
    "DataInici": "13/10/2016",
    "DataFi": "27/10/2016",
    "Assistents": 3500,
    "Web": "http://www.photogenicfestival.cat/",
    "Nota": ""
  },
  {
    "Id": 131,
    "Any": 2016,
    "Ambit": "Audiovisuals",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Assoc. Cultural FICGLB",
    "Edicio": 16,
    "NomDelFestival": "Festival Internacional de Cinema Gai i Lèsbic de Barcelona",
    "DataInici": "14/10/2016",
    "DataFi": "23/10/2016",
    "Assistents": 2356,
    "Web": "http://www.barcelonafilmfestival.org",
    "Nota": ""
  },
  {
    "Id": 132,
    "Any": 2016,
    "Ambit": "Música",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Centre Cultural La Farinera del Clot",
    "Edicio": 9,
    "NomDelFestival": "Say it Loud",
    "DataInici": "14/10/2016",
    "DataFi": "22/10/2016",
    "Assistents": "",
    "Web": "",
    "Nota": ""
  },
  {
    "Id": 133,
    "Any": 2016,
    "Ambit": "Lletres",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Assoc.  Munt de Paraules",
    "Edicio": 7,
    "NomDelFestival": "Munt de Mots. Festival de Narració Oral de Barcelona",
    "DataInici": "17/10/2016",
    "DataFi": "22/10/2016",
    "Assistents": 2424,
    "Web": "http://muntdemots.org",
    "Nota": ""
  },
  {
    "Id": 134,
    "Any": 2016,
    "Ambit": "Multidisciplinaris i altres",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "d-i-n-a i 0100101110101101.org",
    "Edicio": 12,
    "NomDelFestival": "The Influencers",
    "DataInici": "19/10/2016",
    "DataFi": "22/10/2016",
    "Assistents": 2285,
    "Web": "http://theinfluencers.org",
    "Nota": ""
  },
  {
    "Id": 135,
    "Any": 2016,
    "Ambit": "Arts escèniques",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Fundació Catalunya - La Pedrera",
    "Edicio": 6,
    "NomDelFestival": "Dansa Ara",
    "DataInici": "20/10/2016",
    "DataFi": "17/11/2016",
    "Assistents": 582,
    "Web": "",
    "Nota": ""
  },
  {
    "Id": 136,
    "Any": 2016,
    "Ambit": "Arts escèniques",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Assoc.  Escena Poblenou",
    "Edicio": 15,
    "NomDelFestival": "Escena Poblenou",
    "DataInici": "20/10/2016",
    "DataFi": "23/10/2016",
    "Assistents": 4630,
    "Web": "http://www.escenapoblenou.com",
    "Nota": ""
  },
  {
    "Id": 137,
    "Any": 2016,
    "Ambit": "Música",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Zingaria Produccions SL",
    "Edicio": 27,
    "NomDelFestival": "Festival MPB. Festival de Música Popular de Barcelona",
    "DataInici": "20/10/2016",
    "DataFi": "16/12/2016",
    "Assistents": "",
    "Web": "http://www.festivalmpb.eu",
    "Nota": ""
  },
  {
    "Id": 138,
    "Any": 2016,
    "Ambit": "Música",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Music Contact International i Viatges Blanda",
    "Edicio": 13,
    "NomDelFestival": "Festival Coral Cantate Barcelona",
    "DataInici": "21/10/2016",
    "DataFi": "24/10/2016",
    "Assistents": "",
    "Web": "",
    "Nota": ""
  },
  {
    "Id": 139,
    "Any": 2016,
    "Ambit": "Arts escèniques",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Lluïsos de Gràcia i Cia. Mag Oli",
    "Edicio": 7,
    "NomDelFestival": "Màgicus. Festival de Màgia Jove de Barcelona",
    "DataInici": "21/10/2016",
    "DataFi": "23/10/2016",
    "Assistents": 1000,
    "Web": "http://festivalmagicus.blogspot.com.es",
    "Nota": ""
  },
  {
    "Id": 140,
    "Any": 2016,
    "Ambit": "Música",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Primavera Sound",
    "Edicio": 10,
    "NomDelFestival": "San Miguel Primavera Club",
    "DataInici": "21/10/2016",
    "DataFi": "23/10/2016",
    "Assistents": "",
    "Web": "http://www.primaveraclub.com/",
    "Nota": ""
  },
  {
    "Id": 141,
    "Any": 2016,
    "Ambit": "Arts visuals",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Assoc. 48H Open House BCN",
    "Edicio": 7,
    "NomDelFestival": "48H Open House BCN",
    "DataInici": "22/10/2016",
    "DataFi": "23/10/2016",
    "Assistents": 60641,
    "Web": "http://www.48hopenhousebarcelona.org",
    "Nota": ""
  },
  {
    "Id": 142,
    "Any": 2016,
    "Ambit": "Música",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "The Project Music Company",
    "Edicio": 48,
    "NomDelFestival": "Festival Internacional de Jazz de Barcelona",
    "DataInici": "24/10/2016",
    "DataFi": "31/12/2016",
    "Assistents": 34200,
    "Web": "http://www.theproject.es",
    "Nota": ""
  },
  {
    "Id": 143,
    "Any": 2016,
    "Ambit": "Audiovisuals",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Inedit Producciones",
    "Edicio": 14,
    "NomDelFestival": "Beefeater In-Edit Festival",
    "DataInici": "27/10/2016",
    "DataFi": "6/11/2016",
    "Assistents": 30115,
    "Web": "http://www.in-edit.org",
    "Nota": ""
  },
  {
    "Id": 144,
    "Any": 2016,
    "Ambit": "Música",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Orquestra del Caos",
    "Edicio": 15,
    "NomDelFestival": "Zeppelin",
    "DataInici": "28/10/2016",
    "DataFi": "29/10/2016",
    "Assistents": "",
    "Web": "",
    "Nota": ""
  },
  {
    "Id": 145,
    "Any": 2016,
    "Ambit": "Lletres",
    "Titularitat": "Privada",
    "Tipus": "Fires",
    "Organitzador": "Ficòmic",
    "Edicio": 22,
    "NomDelFestival": "Saló del Manga de Barcelona",
    "DataInici": "29/10/2016",
    "DataFi": "1/11/2016",
    "Assistents": 142000,
    "Web": "http://www.ficomic.com",
    "Nota": ""
  },
  {
    "Id": 146,
    "Any": 2016,
    "Ambit": "Arts visuals",
    "Titularitat": "Municipal",
    "Tipus": "Festivals",
    "Organitzador": "Museu Picasso",
    "Edicio": 7,
    "NomDelFestival": "Big Draw",
    "DataInici": "30/10/2016",
    "DataFi": "30/10/2016",
    "Assistents": "",
    "Web": "http://www.bcn.cat/museupicasso/bigdraw/",
    "Nota": ""
  },
  {
    "Id": 147,
    "Any": 2016,
    "Ambit": "Audiovisuals",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Antic Teatre",
    "Edicio": 7,
    "NomDelFestival": "Festival Antic Horror Picture Show",
    "DataInici": "31/10/2016",
    "DataFi": "31/10/2016",
    "Assistents": "",
    "Web": "http://www.anticteatre.com",
    "Nota": ""
  },
  {
    "Id": 148,
    "Any": 2016,
    "Ambit": "Música",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Assoc. AMF",
    "Edicio": 5,
    "NomDelFestival": "AMFest",
    "DataInici": "3/11/2016",
    "DataFi": "5/11/2016",
    "Assistents": 1800,
    "Web": "http://www.amfest.es/",
    "Nota": ""
  },
  {
    "Id": 149,
    "Any": 2016,
    "Ambit": "Música",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Concert Studio",
    "Edicio": 18,
    "NomDelFestival": "Banc Sabadell Festival del Mil·lenni  (desembre)",
    "DataInici": "3/11/2016",
    "DataFi": "31/12/2016",
    "Assistents": 17454,
    "Web": "http://www.festival-millenni.com",
    "Nota": ""
  },
  {
    "Id": 150,
    "Any": 2016,
    "Ambit": "Audiovisuals",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Assoc. Accions 3E",
    "Edicio": 23,
    "NomDelFestival": "FICMA. Festival Internacional de Cinema del Medi Ambient",
    "DataInici": "3/11/2016",
    "DataFi": "10/11/2016",
    "Assistents": "",
    "Web": "http://www.ficma.com",
    "Nota": ""
  },
  {
    "Id": 151,
    "Any": 2016,
    "Ambit": "Música",
    "Titularitat": "Municipal",
    "Tipus": "Festivals",
    "Organitzador": "Centre Cívic Besòs",
    "Edicio": 14,
    "NomDelFestival": "(In)fusión Flamenca. Cicle de Flamenc al Besòs",
    "DataInici": "4/11/2016",
    "DataFi": "26/11/2016",
    "Assistents": 1237,
    "Web": "http://infusionflamenca.cat",
    "Nota": ""
  },
  {
    "Id": 152,
    "Any": 2016,
    "Ambit": "Música",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Centre Cultural Euskal Etxea Barcelona",
    "Edicio": 19,
    "NomDelFestival": "EH SONA! Festival de Música Basca a Barcelona",
    "DataInici": "4/11/2016",
    "DataFi": "26/11/2016",
    "Assistents": "",
    "Web": "http://www.ehsona.com",
    "Nota": ""
  },
  {
    "Id": 153,
    "Any": 2016,
    "Ambit": "Música",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Fund. Victoria de los Ángeles",
    "Edicio": 4,
    "NomDelFestival": "LIED Festival Victoria de los Ángeles",
    "DataInici": "4/11/2016",
    "DataFi": "22/12/2016",
    "Assistents": "",
    "Web": "http://www.lifevictoria.com",
    "Nota": ""
  },
  {
    "Id": 154,
    "Any": 2016,
    "Ambit": "Arts escèniques",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Imaginart",
    "Edicio": 12,
    "NomDelFestival": "El Més Petit de Tots",
    "DataInici": "5/11/2016",
    "DataFi": "20/11/2016",
    "Assistents": 3600,
    "Web": "http://www.elmespetitdetots.cat",
    "Nota": ""
  },
  {
    "Id": 155,
    "Any": 2016,
    "Ambit": "Lletres",
    "Titularitat": "Municipal",
    "Tipus": "Festivals",
    "Organitzador": "Institut de Cultura. Ajuntament de Barcelona",
    "Edicio": 4,
    "NomDelFestival": "Barcelona Novel·la Històrica",
    "DataInici": "7/11/2016",
    "DataFi": "11/11/2016",
    "Assistents": 1407,
    "Web": "",
    "Nota": ""
  },
  {
    "Id": 156,
    "Any": 2016,
    "Ambit": "Audiovisuals",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Assoc. Choreoscope",
    "Edicio": 4,
    "NomDelFestival": "Choreoscope Festival Internacional de Cinema de Dansa de Barcelona",
    "DataInici": "8/11/2016",
    "DataFi": "13/11/2016",
    "Assistents": 1000,
    "Web": "http://choreoscope.com/festival",
    "Nota": ""
  },
  {
    "Id": 157,
    "Any": 2016,
    "Ambit": "Arts escèniques",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "El rei de la màgia",
    "Edicio": 4,
    "NomDelFestival": "Festival Rei de la Màgia",
    "DataInici": "10/11/2016",
    "DataFi": "13/11/2016",
    "Assistents": "",
    "Web": "",
    "Nota": ""
  },
  {
    "Id": 158,
    "Any": 2016,
    "Ambit": "Multidisciplinaris i altres",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "MIRA Associació Cultural",
    "Edicio": 10,
    "NomDelFestival": "MIRA",
    "DataInici": "10/11/2016",
    "DataFi": "12/11/2016",
    "Assistents": 6500,
    "Web": "http://www.mirafestival.com",
    "Nota": ""
  },
  {
    "Id": 159,
    "Any": 2016,
    "Ambit": "Multidisciplinaris i altres",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Fundació Tot Raval",
    "Edicio": 14,
    "NomDelFestival": "Festival de Cultura Raval(s)",
    "DataInici": "11/11/2016",
    "DataFi": "13/11/2016",
    "Assistents": 4300,
    "Web": "http://www.totraval.org",
    "Nota": ""
  },
  {
    "Id": 160,
    "Any": 2016,
    "Ambit": "Audiovisuals",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Assoc. Isla Elefante Projectes Culturals",
    "Edicio": 9,
    "NomDelFestival": "El Meu Primer Festival",
    "DataInici": "12/11/2016",
    "DataFi": "27/11/2016",
    "Assistents": 13000,
    "Web": "http://www.elmeuprimerfestival.com",
    "Nota": ""
  },
  {
    "Id": 161,
    "Any": 2016,
    "Ambit": "Audiovisuals",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "La Fàbrica de Cinema Alternatiu de Barcelona",
    "Edicio": 23,
    "NomDelFestival": "L'Alternativa. Festival de Cinema Independent de Barcelona",
    "DataInici": "14/11/2016",
    "DataFi": "20/11/2016",
    "Assistents": 15000,
    "Web": "http://www.alternativa.cccb.org",
    "Nota": ""
  },
  {
    "Id": 162,
    "Any": 2016,
    "Ambit": "Audiovisuals",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Aj. de BCN i Secretariat d'Entitats de Sants, Hostafrancs i la Bordeta",
    "Edicio": 28,
    "NomDelFestival": "Marató de Cinema Fantàstic i de Terror de Sants",
    "DataInici": "14/11/2016",
    "DataFi": "20/11/2016",
    "Assistents": "",
    "Web": "http://www.cotxeres.org/marato",
    "Nota": ""
  },
  {
    "Id": 163,
    "Any": 2016,
    "Ambit": "Arts escèniques",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Projecte Vaca",
    "Edicio": 16,
    "NomDelFestival": "Novembre Vaca",
    "DataInici": "14/11/2016",
    "DataFi": "29/11/2016",
    "Assistents": "",
    "Web": "http://projectevaca.com",
    "Nota": ""
  },
  {
    "Id": 164,
    "Any": 2016,
    "Ambit": "Multidisciplinaris i altres",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Assoc. El Generador art i creació cultural",
    "Edicio": 6,
    "NomDelFestival": "HOP, trobades de dansa i cultura urbana",
    "DataInici": "17/11/2016",
    "DataFi": "18/12/2016",
    "Assistents": 9000,
    "Web": "",
    "Nota": ""
  },
  {
    "Id": 165,
    "Any": 2016,
    "Ambit": "Multidisciplinaris i altres",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Habitual Video Team",
    "Edicio": 3,
    "NomDelFestival": "INFLUX Festival. Vídeo a Escena",
    "DataInici": "17/11/2016",
    "DataFi": "27/11/2016",
    "Assistents": "",
    "Web": "http://influxfestival.org/",
    "Nota": ""
  },
  {
    "Id": 166,
    "Any": 2016,
    "Ambit": "Audiovisuals",
    "Titularitat": "Consorci o fundació amb presència municipal",
    "Tipus": "Festivals",
    "Organitzador": "Biblioteques de Barcelona",
    "Edicio": 2,
    "NomDelFestival": "Bibliocurts",
    "DataInici": "21/11/2016",
    "DataFi": "1/12/2016",
    "Assistents": 403,
    "Web": "http://bibliocurts.cat/",
    "Nota": ""
  },
  {
    "Id": 167,
    "Any": 2016,
    "Ambit": "Audiovisuals",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Drets en acció",
    "Edicio": 13,
    "NomDelFestival": "Festival de Cinema i Drets Humans de Barcelona",
    "DataInici": "21/11/2016",
    "DataFi": "1/12/2016",
    "Assistents": 12000,
    "Web": "http://www.festivaldecineyderechoshumanos.com",
    "Nota": ""
  },
  {
    "Id": 168,
    "Any": 2016,
    "Ambit": "Arts escèniques",
    "Titularitat": "Consorci o fundació amb presència municipal",
    "Tipus": "Festivals",
    "Organitzador": "Mercat de les Flors i Graner",
    "Edicio": 5,
    "NomDelFestival": "SÂLMON. Talents Europeus en Moviment",
    "DataInici": "24/11/2016",
    "DataFi": "4/12/2016",
    "Assistents": 4846,
    "Web": "http://mercatflors.cat",
    "Nota": ""
  },
  {
    "Id": 169,
    "Any": 2016,
    "Ambit": "Multidisciplinaris i altres",
    "Titularitat": "Municipal",
    "Tipus": "Festivals",
    "Organitzador": "Institut de Cultura. Ajuntament de Barcelona",
    "Edicio": 5,
    "NomDelFestival": "DAU Barcelona",
    "DataInici": "26/11/2016",
    "DataFi": "18/12/2016",
    "Assistents": 19500,
    "Web": "http://daubarcelona.bcn.cat",
    "Nota": ""
  },
  {
    "Id": 170,
    "Any": 2016,
    "Ambit": "Arts escèniques",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Teatre La Puntual SL",
    "Edicio": 12,
    "NomDelFestival": "Festival de Putxinel·lis d'Hivern",
    "DataInici": "2/12/2016",
    "DataFi": "31/12/2016",
    "Assistents": 1306,
    "Web": "http://www.lapuntual.info",
    "Nota": ""
  },
  {
    "Id": 171,
    "Any": 2016,
    "Ambit": "Multidisciplinaris i altres",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Qadar Produccions Culturals",
    "Edicio": 3,
    "NomDelFestival": "Festival Vèrtex BCN",
    "DataInici": "4/12/2016",
    "DataFi": "4/12/2016",
    "Assistents": "",
    "Web": "",
    "Nota": ""
  },
  {
    "Id": 172,
    "Any": 2016,
    "Ambit": "Audiovisuals",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Aula d'Estudis Socials",
    "Edicio": 4,
    "NomDelFestival": "Festival Inclús",
    "DataInici": "12/12/2016",
    "DataFi": "18/12/2016",
    "Assistents": 1418,
    "Web": "http://www.inclus.cat/",
    "Nota": ""
  },
  {
    "Id": 173,
    "Any": 2016,
    "Ambit": "Audiovisuals",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Habitual Video Team",
    "Edicio": "",
    "NomDelFestival": "Flux. Festival de Vídeo d'Autor",
    "DataInici": "12/12/2016",
    "DataFi": "31/12/2016",
    "Assistents": "",
    "Web": "http://www.fluxfestival.org",
    "Nota": ""
  },
  {
    "Id": 174,
    "Any": 2016,
    "Ambit": "Audiovisuals",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "A.I.P.D.A.",
    "Edicio": 6,
    "NomDelFestival": "Festival Internacional de cine Nunes",
    "DataInici": "13/12/2016",
    "DataFi": "17/12/2016",
    "Assistents": "",
    "Web": "",
    "Nota": ""
  },
  {
    "Id": 175,
    "Any": 2016,
    "Ambit": "Arts visuals",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Drap-Art",
    "Edicio": 13,
    "NomDelFestival": "Drap-Art. Festival Internacional de Reciclatge Artístic de Catalunya",
    "DataInici": "16/12/2016",
    "DataFi": "31/12/2016",
    "Assistents": 10000,
    "Web": "http://www.drapart.org",
    "Nota": ""
  },
  {
    "Id": 176,
    "Any": 2016,
    "Ambit": "Audiovisuals",
    "Titularitat": "Privada",
    "Tipus": "Festivals",
    "Organitzador": "Istituto Luce Cinecittà",
    "Edicio": 5,
    "NomDelFestival": "Mostra de Cinema Italià de Barcelona. MCIB",
    "DataInici": "16/12/2016",
    "DataFi": "21/12/2016",
    "Assistents": "",
    "Web": "",
    "Nota": ""
  }
];


}
